package:$1:
  - changed-files:
      - packages/([^/]+)/.*

examples:
  - changed-files:
      - examples/**/*

feature:
  - head-branch: ['^feature', 'feature']

issue:
  - head-branch: ['^fix', 'fix']

dependency:
  - head-branch: ['^deps', 'deps']

configuration:
  - changed-files:
      - .circleci/**/*
      - .dependabot/**/*
      - .github/**/*
      - tsconfig.base.json
      - tsconfig.json
      - .eslintrc.cjs
      - .prettierrc
      - lerna.json
      - .nvrmrc
