package:$1:
  - changed-files:
      - any-glob-to-any-file: packages/([^/]+)/.*

examples:
  - changed-files:
      - any-glob-to-any-file: examples/**/*

feature:
  - head-branch: ['^feature', 'feature']

issue:
  - head-branch: ['^fix', 'fix']

dependency:
  - head-branch: ['^deps', 'deps']

configuration:
  - changed-files:
      - any-glob-to-any-file:
          - .circleci/**/*
          - .dependabot/**/*
          - .github/**/*
          - tsconfig.base.json
          - tsconfig.json
          - .eslintrc.cjs
          - .prettierrc
          - lerna.json
          - .nvrmrc
