import type { Metadata } from 'next';
import { draftMode } from 'next/headers';
import { ContentfulPreviewProvider } from '../components/contentful-preview-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isEnabled } = await draftMode();

  return (
    <ContentfulPreviewProvider
      locale="en-US"
      enableInspectorMode={isEnabled}
      enableLiveUpdates={isEnabled}
    >
      <html lang="en">
        <body>{children}</body>
      </html>
    </ContentfulPreviewProvider>
  );
}
