import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { draftMode } from 'next/headers';
import Script from 'next/script';

import '@contentful/live-preview/style.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next app with app router and reload entry change',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const { isEnabled } = draftMode();

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      {isEnabled && <Script src="/live-preview.mjs" />}
    </html>
  );
}
